// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_queries.sql

package repository

import (
	"context"
)

const getAccessToken = `-- name: GetAccessToken :one
SELECT "accessToken", "providerId" FROM account WHERE "userId" = $1
`

type GetAccessTokenRow struct {
	AccessToken *string
	ProviderId  string
}

func (q *Queries) GetAccessToken(ctx context.Context, userid string) (GetAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, getAccessToken, userid)
	var i GetAccessTokenRow
	err := row.Scan(&i.AccessToken, &i.ProviderId)
	return i, err
}
