// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_queries.sql

package repository

import (
	"context"
)

type AddReposParams struct {
	UserId       string
	GithubRepoId int64
	RepoName     string
}

const checkRepoLimit = `-- name: CheckRepoLimit :one
SELECT "allowedRepos" from user_profiles WHERE "userId" = $1
`

func (q *Queries) CheckRepoLimit(ctx context.Context, userid string) (int32, error) {
	row := q.db.QueryRow(ctx, checkRepoLimit, userid)
	var allowedRepos int32
	err := row.Scan(&allowedRepos)
	return allowedRepos, err
}

const decrementRepoLimit = `-- name: DecrementRepoLimit :one
UPDATE user_profiles
SET "allowedRepos" = "allowedRepos" - $1
WHERE "userId" = $2 AND "allowedRepos" >= $1
RETURNING "allowedRepos"
`

type DecrementRepoLimitParams struct {
	AllowedRepos int32
	UserId       string
}

func (q *Queries) DecrementRepoLimit(ctx context.Context, arg DecrementRepoLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, decrementRepoLimit, arg.AllowedRepos, arg.UserId)
	var allowedRepos int32
	err := row.Scan(&allowedRepos)
	return allowedRepos, err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT "accessToken", "providerId" FROM account WHERE "userId" = $1
`

type GetAccessTokenRow struct {
	AccessToken *string
	ProviderId  string
}

func (q *Queries) GetAccessToken(ctx context.Context, userid string) (GetAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, getAccessToken, userid)
	var i GetAccessTokenRow
	err := row.Scan(&i.AccessToken, &i.ProviderId)
	return i, err
}

const getProjects = `-- name: GetProjects :many
SELECT "githubRepoId", "repoName" FROM repositories WHERE "userId" = $1
`

type GetProjectsRow struct {
	GithubRepoId int64
	RepoName     string
}

func (q *Queries) GetProjects(ctx context.Context, userid string) ([]GetProjectsRow, error) {
	rows, err := q.db.Query(ctx, getProjects, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectsRow
	for rows.Next() {
		var i GetProjectsRow
		if err := rows.Scan(&i.GithubRepoId, &i.RepoName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
