// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_queries.sql

package repository

import (
	"context"
)

const getAccessToken = `-- name: GetAccessToken :one
SELECT "accessToken" FROM account WHERE "userId" = $1
`

func (q *Queries) GetAccessToken(ctx context.Context, userid string) (*string, error) {
	row := q.db.QueryRow(ctx, getAccessToken, userid)
	var accessToken *string
	err := row.Scan(&accessToken)
	return accessToken, err
}
