// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForAddRepos implements pgx.CopyFromSource.
type iteratorForAddRepos struct {
	rows                 []AddReposParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddRepos) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddRepos) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserId,
		r.rows[0].GithubRepoId,
		r.rows[0].RepoName,
	}, nil
}

func (r iteratorForAddRepos) Err() error {
	return nil
}

func (q *Queries) AddRepos(ctx context.Context, arg []AddReposParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"repositories"}, []string{"userId", "githubRepoId", "repoName"}, &iteratorForAddRepos{rows: arg})
}
