// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: middleware.sql

package repository

import (
	"context"
	"time"
)

const getInfoFromSession = `-- name: GetInfoFromSession :one
SELECT "userId", "expiresAt" FROM session WHERE token = $1
`

type GetInfoFromSessionRow struct {
	UserId    string
	ExpiresAt time.Time
}

func (q *Queries) GetInfoFromSession(ctx context.Context, token string) (GetInfoFromSessionRow, error) {
	row := q.db.QueryRow(ctx, getInfoFromSession, token)
	var i GetInfoFromSessionRow
	err := row.Scan(&i.UserId, &i.ExpiresAt)
	return i, err
}
