// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	UserId                string
	Issuer                string
	AccountId             string
	ProviderId            string
	AccessToken           *string
	RefreshToken          *string
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	Scope                 *string
	IdToken               *string
	Password              *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Session struct {
	ID        string
	UserId    string
	Token     string
	ExpiresAt time.Time
	IpAddress *string
	UserAgent *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
